# Generated by Django 3.0 on 2020-11-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0002_donation_request_connector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_request',
            name='connector',
        ),
    ]
