# Generated by Django 3.0 on 2020-11-20 20:05

from django.db import migrations, models
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0003_remove_donation_request_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_history',
            name='donation_request_user',
            field=models.CharField(default=django_currentuser.middleware.get_current_authenticated_user, max_length=50),
        ),
    ]
