# Generated by Django 3.0 on 2020-11-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySystem', '0004_donation_history_donation_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation_history',
            old_name='donation_request_user',
            new_name='current_donor',
        ),
    ]
